# GitHub Action that builds Apple iOS project using xcodebuild command

name: Builds Apple iOS project using CI/CD process

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  Build-iOS-Project:
    runs-on: macos-latest
    name: Build iOS Project
    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3

      - name: Print out help command from xcodebuild
        run: xcodebuild -help

      - name: List out project from Apple iOS xcode project
        run: xcodebuild -list -project HelloWorld.xcodeproj

      - name: Clean iOS Project
        run: xcodebuild clean

      - name: Archive the ios project
        run: xcodebuild archive -scheme HelloWorld -sdk iphoneos -allowProvisioningUpdates -archivePath HelloWorld.xcarchive

      